name: publish
on: [push]
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: npm install -g sass
      - run: sudo sh -c 'apt-get update && apt-get install -y racket make'

      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
          lfs: true

      - run: make

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          keep_files: true
          cname: iometelabs.io
